services:
  db:
    image: postgres:16
    container_name: prajascan_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prajascan
    ports:
      - "5432:5432"
    volumes:
      - prajascan_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: prajascan_redis
    ports:
      - "6379:6379"

volumes:
  prajascan_pg_data: